### ISSUE TITLE
BUG: Testnet, interface broken after connecting wrong Native Address.

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/teloscan#70]
**Describe the bug**
After connecting an invalid Native Address, the interface is stuck, ie can't reconnect, no error given in interface.

**To Reproduce**
1: Click Connect
2: Select Native Wallet
3: Select a non existing address
4: Try to reconnect with an exosting.

**Expected behavior**
Error message should be provided to the user, interface should be reset for a new connection attempt.

**Screenshots**
`Error: No address associated with doublewabbit
    at m.<anonymous> (vendor.99856eba.js:300:9289)
    at Generator.next (<anonymous>)
    at c (vendor.99856eba.js:300:1794)`

No information is given to the user.

**Environment Used**
 - OS: OSX
 - Browser Chrome

**Comment by DestinyDevTeam** [comment]
Soft Refresh of Browser Window, does not help.

**Comment by DestinyDevTeam** [comment]
Hard refresh of Browser Window, does not help.

**Comment by DestinyDevTeam** [comment]
Restarting Browser, does not help.

**Comment by poplexity** [comment]
This is fixed.

**Comment by DestinyDevTeam** [comment]
Tested, and working as expected. Interface not broken, able to reconnect.

**Comment by DestinyDevTeam** [comment]
**Description**
Reverse Test, Connecting an Existing Account fails - Uncertain if this is an environment issue or not.
Clearing Cache enables Connection.

**Reproduce**
1: Connect an existing EVM account with Anchor
2: Navigate away from Page
3: Try to Reconnect

**Console Log Error**
ESR:
`Launched external handler for 'esr:gz2QPUjDQACFja0idHHwZxG5QaGKvaTNpW2sSxWp0lRBA7qV83olR2Iu3J0KoghugpsoOCkIDq7SUTq61KmuCu6Cg5OL-O_68d774GnDVz0j0c7hwM1on3vU7B5_fnhvBJL7l_Ze-vh16ix20N_RBs5FZ0dnwVMqkpO6TtYgDonHBQxY6OvIRrlcHpMUsutGCpl1K5W3cSZlZmtpSpBRwxkzHv-KtrT_tVirdP16ev-8_9a4HSzqS-2Vl92BE-fp8a5ndqHVXOo914rfDudLYUITIjAt-JakwhU4lBEX6hNnoAUqfJsFAdYtaIBkBRMWKi69ApgPFQ3AJwCLy2AVpI1q2qrmxkAxigK6QtfKTOmWmYNmFiTLc27FmQAB8ykoUeLzMTDjCb5OdduGBkR5hGAegWVcx4L9trok4RHtdWnAJcEhcKlUIVUJiddptUY3GaGalhBUbYiwGmHlDf0dqH6SUP1WIeP6Bw'.`

`Detected alien instance of checksum256, this usually means more than one version of @greymass/eosio has been included in your bundle.`

`vendor.99856eba.js:114 ReferenceError: evmAccount is not defined
    at c.ualLogin (1.fece6f5a.js:1:7157)`

Clearing Cache unlocks Connect Button
After signing, the Wallet Modal is still open.

**Comment by DestinyDevTeam** [comment]
**Description**
Reverse Test, Connecting an Existing Account fails - Uncertain if this is an environment issue or not.
Clearing Cache enables Connection.

**Reproduce**
1: Connect an existing EVM account with Anchor
2: Navigate away from Page
3: Try to Reconnect

**Console Log Error**
ESR:
`Launched external handler for 'esr:gz2QPUjDQACFja0idHHwZxG5QaGKvaTNpW2sSxWp0lRBA7qV83olR2Iu3J0KoghugpsoOCkIDq7SUTq61KmuCu6Cg5OL-O_68d774GnDVz0j0c7hwM1on3vU7B5_fnhvBJL7l_Ze-vh16ix20N_RBs5FZ0dnwVMqkpO6TtYgDonHBQxY6OvIRrlcHpMUsutGCpl1K5W3cSZlZmtpSpBRwxkzHv-KtrT_tVirdP16ev-8_9a4HSzqS-2Vl92BE-fp8a5ndqHVXOo914rfDudLYUITIjAt-JakwhU4lBEX6hNnoAUqfJsFAdYtaIBkBRMWKi69ApgPFQ3AJwCLy2AVpI1q2qrmxkAxigK6QtfKTOmWmYNmFiTLc27FmQAB8ykoUeLzMTDjCb5OdduGBkR5hGAegWVcx4L9trok4RHtdWnAJcEhcKlUIVUJiddptUY3GaGalhBUbYiwGmHlDf0dqH6SUP1WIeP6Bw'.`

`Detected alien instance of checksum256, this usually means more than one version of @greymass/eosio has been included in your bundle.`

`vendor.99856eba.js:114 ReferenceError: evmAccount is not defined
    at c.ualLogin (1.fece6f5a.js:1:7157)`

Clearing Cache unlocks Connect Button
After signing, the Wallet Modal is still open.

**Comment by DestinyDevTeam** [comment]
I also noticed that we have a dependency in package.json to ual-anchor 1.0.0 whereas the latest is 1.1.4 ?

**Comment by poplexity** [comment]
This should be fixed now.

**Comment by DestinyDevTeam** [comment]
**Tests**

1: Connecting Valid Account - OK
2: Connecting InValid Account - OK ( Produce a human readable Error )

None of these break the connection or connecting reattempt feature.

3: Navigating back and forth, also cross-site - OK
4: Closing Browser and ReOpening - OK

Connection is persistent for #3 and #4
